# Generated by Django 3.0.1 on 2020-01-01 01:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boast', models.BooleanField()),
                ('post', models.CharField(max_length=280)),
                ('up_votes', models.IntegerField(default=0)),
                ('down_votes', models.IntegerField(default=0)),
                ('creation_time', models.DateTimeField(default=datetime.datetime(2020, 1, 1, 1, 55, 4, 413488, tzinfo=utc))),
            ],
        ),
    ]
